'use client';

import { PixelArt, type Palette } from '@/client/lib/pixel';

/** Which aid a scene belongs to. Mirrors LifelineType in the show page. */
export type LifelineType = 'fifty' | 'skip' | 'audience' | 'students';

/**
 * Pixel-art scene shown when an aid is spent: 64x40 grids of characters, one
 * per pixel. Regenerate with `python3 scripts/gen-lifeline-scenes.py`.
 */
const PALETTE: Palette = {
  o: '#241d30',
  s: '#f2bd94',
  S: '#d1906a',
  q: '#241d30',
  m: '#8a4a52',
  1: '#3a2c26',
  2: '#8a5a34',
  3: '#d8c48a',
  4: '#c3cbe4',
  5: '#4a7ac4',
  6: '#c4574a',
  7: '#4aa87a',
  8: '#a06fc0',
  9: '#d99b12',
  b: '#111a3d',
  B: '#1b2450',
  w: '#8a5f3a',
  W: '#5f3f26',
  p: '#f6f8ff',
  P: '#c9d3ee',
  r: '#de5d60',
  g: '#5ed99a',
  c: '#3ce0e6',
  G: '#ffd24a',
};

const SCENES: Record<LifelineType, string[]> = {
  fifty: [
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBoooooooooooooBBBoooooooooooooBBBoooooooooooooBBBoooooooooooooB',
    'BBopppppppppppoBBBopppppppppppoBBBopppppppppppoBBBopppppppppppoB',
    'BBoppcppppppppoBBBoppPppppppppoBBBoppPppppppppoBBBoppcppppppppoB',
    'BBopppppppppppoBBBorrppppppprroBBBorrppppppprroBBBopppppppppppoB',
    'BBopppppppppppoBBBorrrppppprrroBBBorrrppppprrroBBBopppppppppppoB',
    'BBoppppcccpppppBBBoprrrPPPrrrppBBBoprrrPPPrrrppBBBoppppcccpppppB',
    'BBopppcccccppppBBBopprrrPrrrpppBBBopprrrPrrrpppBBBopppcccccppppB',
    'BBoppcccccccpppBBBoppPrrrrrPpppBBBoppPrrrrrPpppBBBoppcccccccpppB',
    'BBopppcccccppppBBBopppPrrrPppppBBBopppPrrrPppppBBBopppcccccppppB',
    'BBoppppcccpppppBBBoppprrrrrppppBBBoppprrrrrppppBBBoppppcccpppppB',
    'BBopppppppppppoBBBopprrrprrrppoBBBopprrrprrrppoBBBopppppppppppoB',
    'BBopppppppppppoBBBoprrrppprrrpoBBBoprrrppprrrpoBBBopppppppppppoB',
    'BBopppppppppppoBBBorrrppppprrroBBBorrrppppprrroBBBopppppppppppoB',
    'BBopppppppppppoBBBorrppppppprroBBBorrppppppprroBBBopppppppppppoB',
    'BBoppppppppcppoBBBoppppppppPppoBBBoppppppppPppoBBBoppppppppcppoB',
    'BBopppppppppppoBBBopppppppppppoBBBopppppppppppoBBBopppppppppppoB',
    'BBoooooooooooooBBBoooooooooooooBBBoooooooooooooBBBoooooooooooooB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
  skip: [
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BoooooooooooooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoooooooooooooBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBopppppppppppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoppGppppppppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBopppppppppppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBccBBBBBBBBBBBopppppppppppoBBBBBBB',
    'BoPPPPPPPPPPPPBBBBBBBBBBBBBBBBBcccBBBBBBBBBBoppppGGGpppppBBBBBBB',
    'BoPPPPPPPPPPPPBBBBBBBBBBBBccccccccccBBBBBBBBopppGGGGGppppBBBBBBB',
    'BoPPPPPPPPPPPPBBBBBBBBBBBBcccccccccccBBBBBBBoppGGGGGGGpppBBBBBBB',
    'BoPPPPPPPPPPPPBBBBBBBBBBBBccccccccccccBBBBBBopppGGGGGppppBBBBBBB',
    'BoPPPPPPPPPPPPBBBBBBBBBBBBcccccccccccBBBBBBBoppppGGGpppppBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBccccccccccBBBBBBBBopppppppppppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBcccBBBBBBBBBBopppppppppppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBccBBBBBBBBBBBopppppppppppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBopppppppppppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoppppppppGppoBBBBBBB',
    'BoPPPPPPPPPPPoBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBopppppppppppoBBBBBBB',
    'BoooooooooooooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBoooooooooooooBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  ],
  audience: [
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbbbbbbbbbbbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbbbbbbbbbbbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbbbbbbbbbbbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbbbbbbbbbbbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbgggggggggbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbgggggggggbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbgggggggggbbbbbGGGGGGGGGbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbcccccccccbbbbbgggggggggbbbbbGGGGGGGGGbbbbbrrrrrrrrrbbbbbbb',
    'bbbbbbcccccccccbbbbbgggggggggbbbbbGGGGGGGGGbbbbbrrrrrrrrrbbbbbbb',
    'bbbbbbcccccccccbbbbbgggggggggbbbbbGGGGGGGGGbbbbbrrrrrrrrrbbbbbbb',
    'bbbbbbcccccccccbbbbbgggggggggbbbbbGGGGGGGGGbbbbbrrrrrrrrrbbbbbbb',
    'bbbbbbooooooooobbbbbooooooooobbbbbooooooooobbbbbooooooooobbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbooobbbbbooobbbbbooobbbbbooobbbbbooobbbbbooobbbbbooobbbbbooobb',
    'bbo111obbbo222obbbo333obbbo444obbbo111obbbo222obbbo333obbbo444ob',
    'bboqsqobbboqsqobbboqsqobbboqsqobbboqsqobbboqsqobbboqsqobbboqsqob',
    'bbbosobbbbbosobbbbbosobbbbbosobbbbbosobbbbbosobbbbbosobbbbbosobb',
    'bbo555obbbo666obbbo777obbbo999obbbo555obbbo666obbbo777obbbo999ob',
    'bbo555obbbo666obbbo777obbbo999obbbo555obbbo666obbbo777obbbo999ob',
    'bbooooobbbooooobbbooooobbbooooobbbooooobbbooooobbbooooobbbooooob',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbooobbbbbooobbbbbooobbbbbooobbbbbooobbbbbooobbbbbooobbbbbb',
    'bbbbbbo111obbbo222obbbo333obbbo444obbbo111obbbo222obbbo333obbbbb',
    'bbbbbboqsqobbboqsqobbboqsqobbboqsqobbboqsqobbboqsqobbboqsqobbbbb',
    'bbbbbbbosobbbbbosobbbbbosobbbbbosobbbbbosobbbbbosobbbbbosobbbbbb',
    'bbbbbbo999obbbo555obbbo777obbbo666obbbo999obbbo555obbbo777obbbbb',
    'bbbbbbo999obbbo555obbbo777obbbo666obbbo999obbbo555obbbo777obbbbb',
    'bbbbbbooooobbbooooobbbooooobbbooooobbbooooobbbooooobbbooooobbbbb',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  ],
  students: [
    'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBoooooooBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBopppppppoBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBopqpqpqpoBBBBBBBBBBBBBBBBBBoooooooBBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBopppppppoBBBBBBBBBBBBBBBBBopppppppoBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBoooooooBBBBBBBBBBBBBBBBBBopqpqpqpoBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBopoBBBBBBBBBBBBBBBBBBBBBopppppppoBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBBBoBBBBBBBBBBBBBBBBBBBBBBBoooooooBBBBBBBBBBBBBBBB',
    'BBBBBBBBoooooBBBBBBBBBBBBBBBBoooooBBBBBBBBopoBBBBBoooooBBBBBBBBB',
    'BBBBBBBo22222oBBBBBBBBBBBBBBo11111oBBBBBBBBoBBBBBo33333oBBBBBBBB',
    'BBBBBBo2222222oBBBBBBBBBBBBo1111111oBBBBBBBBBBBBo3333333oBBBBBBB',
    'BBBBBBo2sssss2oBBBBBBBBBBBBo1sssss1oBBBBBBBBBBBBo3sssss3oBBBBBBB',
    'BBBBBBosqsssqsoBBBBBBBBBBBBosqsssqsoBBBBBBBBBBBBosqsssqsoBBBBBBB',
    'BBBBBBosssssssoBBBBBBBBBBBBosssssssoBBBBBBBBBBBBosssssssoBBBBBBB',
    'BBBBBBosssmsssoBBBBBBBBBBBBosssmsssoBBBBBBBBBBBBosssmsssoBBBBBBB',
    'BBBBBBBosssssoBBBBBBBBBBBBBBosssssoBBBBBBBBBBBBBBosssssoBBBBBBBB',
    'BBBBBBBBosssoBBBBBBBBBBBBBBBBosssoBBBBBBBBBBBBBBBBosssoBBBBBBBBB',
    'BBBBBBo5555555oBBBBBBBBBBBBo7777777oBBBBBBBBBBBBo8888888oBBBBBBB',
    'BBBBBBo5555555oBBooooooooBBo7777777oBBBooooooooBo8888888oBBBBBBB',
    'BBBBBBo5555555oBBopppppPoBBo7777777oBBBopppppPoBo8888888oBBBBBBB',
    'BBBBBBo5555555oBBoPPPPPPoBBo7777777oBBBoPPPPPPoBo8888888oBBBBBBB',
    'BBBBBBoooooooooBBooooooooBBoooooooooBBBooooooooBoooooooooBBBBBBB',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
  ],
};

export function ShowLifelineScene({ type }: { type: LifelineType }) {
  return <PixelArt rows={SCENES[type]} palette={PALETTE} className="show-scene-art" />;
}
